model: vae
epochs: 10
learning_rate: 4.5e-6
batch_size: 64
codebook_dim: 64
num_tokens: 8192
hidden_dim: 64
num_res_blocks: 8
loss_type: l1
lr_decay: True
precision: 16
backup: True
log_images: True
num_workers: 16
train_dir: 'datasets/imagenet1k/train/'
val_dir: 'datasets/imagenet1k/val/'
image_log_steps: 1000
pretrained_path: wavenet.ckpt


